// budget-app-angular/src/app/features/component/transaction/transaction-form/transaction-form.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { ReactiveFormsModule, FormGroup, FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { TransactionService } from '../services/transaction.service';

@Component({
  selector: 'app-transaction-form',
  standalone: true,
  imports: [ReactiveFormsModule, CommonModule],
  templateUrl: './transaction-form.component.html',
  styleUrl: './transaction-form.component.css'
})
export class TransactionFormComponent implements OnInit {
  transactionForm: FormGroup;
  isEditMode = false;
  transactionId: number | null = null;

  availableCategories: string[] = [];
  incomeCategories: string[] = ['Salary', 'Freelance', 'Investment', 'Bonus'];
  expenseCategories: string[] = ['Groceries', 'Entertainment', 'Health', 'Food', 'Shopping', 'Utilities'];

  constructor(
    private fb: FormBuilder,
    private transactionService: TransactionService,
    private route: ActivatedRoute,
    private router: Router
  ) {
    this.transactionForm = this.fb.group({
      type: ['Expense', Validators.required],
      category: ['', Validators.required],
      amount: ['', [Validators.required, Validators.min(0.01)]],
      createdDate: [this.formatDate(new Date()), Validators.required],
    });
  }

  ngOnInit(): void {
    // Determine mode and ID from the route snapshot
    this.transactionId = Number(this.route.snapshot.paramMap.get('id'));
    this.isEditMode = !!this.transactionId;

    if (this.isEditMode) {
      this.transactionService.getById(this.transactionId).subscribe((transaction) => {
        if (transaction) {
          this.transactionForm.patchValue({
            ...transaction,
            createdDate: this.formatDate(transaction.createdDate)
          });
          this.updateCategories(); // Update categories based on fetched type
        }
      });
    } else {
      this.updateCategories(); // Set initial categories for 'add' mode
    }

    // Listen for changes on the 'type' dropdown
    this.transactionForm.get('type')?.valueChanges.subscribe(() => {
      this.updateCategories(true); // Reset category when type changes
    });
  }

  updateCategories(resetCategory: boolean = false): void {
    const type = this.transactionForm.get('type')?.value;
    this.availableCategories = type === 'Income' ? this.incomeCategories : this.expenseCategories;
    if (resetCategory) {
      this.transactionForm.get('category')?.setValue('');
    }
  }

  onSubmit(): void {
    if (this.transactionForm.invalid) {
      this.transactionForm.markAllAsTouched();
      return;
    }

    const formValue = this.transactionForm.value;
    const operation$ = this.isEditMode && this.transactionId
      ? this.transactionService.update(this.transactionId, formValue)
      : this.transactionService.create(formValue);

    operation$.subscribe(() => {
      this.router.navigate(['/transactions']);
    });
  }

  onCancel(): void {
    this.router.navigate(['/transactions']);
  }

  // Helper functions for date formatting
  formatDate(date: string | Date): string {
    const d = new Date(date);
    // Adjust for timezone offset to get the correct local date
    d.setMinutes(d.getMinutes() - d.getTimezoneOffset());
    return d.toISOString().split('T')[0];
  }

  getTodayDate(): string {
    return this.formatDate(new Date());
  }
}

<div class="container py-4">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow-sm">
                <div class="card-header bg-light py-3">
                    <h3 class="card-title mb-0 fw-semibold">{{ isEditMode ? 'Edit Transaction' : 'Add Transaction' }}
                    </h3>
                </div>
                <div class="card-body p-4">
                    <form [formGroup]="transactionForm" (ngSubmit)="onSubmit()">
                        <div class="mb-4">
                            <label for="type" class="form-label fw-medium">Type</label>
                            <select class="form-select form-select-lg" id="type" formControlName="type">
                                <option value="Expense">Expense</option>
                                <option value="Income">Income</option>
                            </select>
                        </div>
                        <div class="mb-4">
                            <label for="category" class="form-label fw-medium">Category</label>
                            <select class="form-select form-select-lg" id="category" formControlName="category">
                                <option value="" disabled>Select a category</option>
                                <option *ngFor="let category of availableCategories" [value]="category">
                                    {{ category }}
                                </option>
                            </select>
                        </div>
                        <div class="mb-4">
                            <label for="amount" class="form-label fw-medium">Amount</label>
                            <div class="input-group">
                                <span class="input-group-text">INR</span>
                                <input type="number" class="form-control form-control-lg" id="amount"
                                    formControlName="amount" />
                            </div>
                        </div>
                        <div class="mb-4">
                            <label for="date" class="form-label fw-medium">Date</label>
                            <input type="date" class="form-control form-control-lg" id="date"
                                formControlName="createdDate" [max]="getTodayDate()" />
                        </div>
                        <div class="d-flex justify-content-end gap-4">
                            <button type="button" class="btn btn-secondary btn-lg" (click)="onCancel()">
                                Cancel
                            </button>
                            <button type="submit" class="btn btn-primary btn-lg" [disabled]="transactionForm.invalid">
                                {{ isEditMode ? 'Save Changes' : 'Add Transaction' }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

// budget-app-react/src/features/component/transaction/transaction-form/TransactionForm.tsx
import { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { useNavigate, useParams } from 'react-router-dom';
import axios from 'axios';
import { TransactionInterface } from '../models/TransactionInterface';

const API_URL = process.env.REACT_APP_API_URL || 'https://localhost:7290/api';

const incomeCategories = ['Salary', 'Freelance', 'Investment', 'Bonus'];
const expenseCategories = ['Groceries', 'Entertainment', 'Health', 'Food', 'Shopping', 'Utilities'];

export const TransactionForm = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const isEditMode = !!id;
  const { register, handleSubmit, watch, setValue, formState: { errors } } = useForm<TransactionInterface>();
  const type = watch('type');

  useEffect(() => {
    if (isEditMode) {
      const fetchTransaction = async () => {
        try {
          const token = localStorage.getItem('auth_token');
          const response = await axios.get(`${API_URL}/Transaction/${id}`, {
            headers: { Authorization: `Bearer ${token}` }
          });
          const transaction = response.data;
          setValue('type', transaction.type);
          setValue('category', transaction.category);
          setValue('amount', transaction.amount);
          setValue('createdDate', new Date(transaction.createdDate).toISOString().split('T')[0]);
        } catch (error) {
          console.error('Failed to fetch transaction', error);
        }
      };
      fetchTransaction();
    } else {
      setValue('createdDate', new Date().toISOString().split('T')[0]);
    }
  }, [id, isEditMode, setValue]);


  const onSubmit = async (data: TransactionInterface) => {
    try {
      const token = localStorage.getItem('auth_token');
      if (isEditMode) {
        await axios.put(`${API_URL}/Transaction/${id}`, data, {
          headers: { Authorization: `Bearer ${token}` }
        });
      } else {
        await axios.post(`${API_URL}/Transaction`, data, {
          headers: { Authorization: `Bearer ${token}` }
        });
      }
      navigate('/transactions');
    } catch (error) {
      console.error('Failed to save transaction', error);
    }
  };

  return (
    <div className="container py-4">
      <div className="row justify-content-center">
        <div className="col-md-8 col-lg-6">
          <div className="card shadow-sm">
            <div className="card-header bg-light py-3">
              <h3 className="card-title mb-0 fw-semibold">{isEditMode ? 'Edit Transaction' : 'Add Transaction'}</h3>
            </div>
            <div className="card-body p-4">
              <form onSubmit={handleSubmit(onSubmit)}>
                <div className="mb-4">
                  <label htmlFor="type" className="form-label fw-medium">Type</label>
                  <select className="form-select form-select-lg" id="type" {...register('type')}>
                    <option value="Expense">Expense</option>
                    <option value="Income">Income</option>
                  </select>
                </div>
                <div className="mb-4">
                  <label htmlFor="category" className="form-label fw-medium">Category</label>
                  <select className={`form-select form-select-lg ${errors.category ? 'is-invalid' : ''}`} id="category" {...register('category', { required: 'Category is required' })}>
                    <option value="">Select a category</option>
                    {(type === 'Income' ? incomeCategories : expenseCategories).map(category => (
                      <option key={category} value={category}>{category}</option>
                    ))}
                  </select>
                  {errors.category && <div className="invalid-feedback">{errors.category.message}</div>}
                </div>
                <div className="mb-4">
                  <label htmlFor="amount" className="form-label fw-medium">Amount</label>
                  <div className="input-group">
                    <span className="input-group-text">INR</span>
                    <input
                      type="number"
                      className={`form-control form-control-lg ${errors.amount ? 'is-invalid' : ''}`}
                      id="amount"
                      {...register('amount', { required: 'Amount is required', valueAsNumber: true, min: { value: 0.01, message: 'Amount must be a positive number' } })}
                    />
                  </div>
                  {errors.amount && <div className="invalid-feedback d-block">{errors.amount.message}</div>}
                </div>
                <div className="mb-4">
                  <label htmlFor="date" className="form-label fw-medium">Date</label>
                  <input type="date" className={`form-control form-control-lg ${errors.createdDate ? 'is-invalid' : ''}`} id="date" {...register('createdDate', { required: 'Date is required' })} />
                  {errors.createdDate && <div className="invalid-feedback">{errors.createdDate.message}</div>}
                </div>
                <div className="d-flex justify-content-end gap-4">
                  <button type="button" className="btn btn-secondary btn-lg" onClick={() => navigate('/transactions')}>
                    Cancel
                  </button>
                  <button type="submit" className="btn btn-primary btn-lg">
                    {isEditMode ? 'Save Changes' : 'Add Transaction'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
