// budget-app-react/src/common/header/Header.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../core/hooks/useAuth';

export const Header = () => {
  const { isAuthenticated, logout } = useAuth();

  return (
    <nav className="navbar navbar-expand-lg navbar-light bg-black">
      <div className="container-fluid">
        <Link className="navbar-brand text-light" style={{ textDecoration: 'none', outline: 'none' }} to="/">BudgetApp</Link>
        <div className="collapse navbar-collapse">
          <ul className="navbar-nav ms-auto">
            {isAuthenticated && (
              <li className="nav-item">
                <button className="btn btn-outline-light" onClick={logout}>Logout</button>
              </li>
            )}
          </ul>
        </div>
      </div>
    </nav>
  );
};

// budget-app-angular/src/app/common/header/header.component.ts
import { CommonModule } from '@angular/common';
import { Component, Signal } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../features/component/signup-login/services/auth.service';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterModule, CommonModule],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {

  isAuthenticated: Signal<boolean>;

  constructor(private authService: AuthService) {
    this.isAuthenticated = this.authService.isAuthenticated;
  }

  logout(): void {
    this.authService.logout();
  }

}


<nav class="navbar navbar-expand-lg navbar-light bg-black">
    <div class="container-fluid">
        <a class="navbar-brand text-light" style="text-decoration: none; outline: none" [routerLink]="'/'">BudgetApp</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item" *ngIf="isAuthenticated()">
                    <button class="btn btn-outline-light" (click)="logout()">Logout</button>
                </li>
            </ul>
        </div>
    </div>
</nav>
