// budget-app-react/src/features/component/signup-login/SignupLogin.tsx
import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../../../core/hooks/useAuth';
import { User } from './models/User';

interface SignupLoginProps {
  isLoginMode: boolean;
}

export const SignupLogin = ({ isLoginMode }: SignupLoginProps) => {
  const { register: registerUser, login, } = useAuth();
  const navigate = useNavigate();
  const [errorMessage, setErrorMessage] = useState('');
  const { register, handleSubmit, formState: { errors }, watch } = useForm<User>();
  const password = watch("password");

  const onSubmit = async (data: User) => {
    setErrorMessage('');
    try {
      if (isLoginMode) {
        await login(data);
      } else {
        await registerUser(data);
      }
      navigate('/transactions');
    } catch (error: any) {
      if (error.response?.data?.message) {
        setErrorMessage(error.response.data.message);
      } else if (error.response?.data) {
        setErrorMessage(error.response.data);
      } else {
        setErrorMessage('An unexpected error occurred.');
      }
    }
  };

  return (
    <div className="container">
      <div className="row justify-content-center">
        <div className="col-md-6 col-lg-4">
          <div className="card mt-5">
            <div className="card-header bg-primary bg-opacity-75">
              <h3 className="card-title mb-0 text-white">{isLoginMode ? 'Login' : 'Sign Up'}</h3>
            </div>
            <div className="card-body">
              {errorMessage && <div className="alert alert-danger">{errorMessage}</div>}
              <form onSubmit={handleSubmit(onSubmit)}>
                <div className="mb-3">
                  <label htmlFor="email" className="form-label">Email</label>
                  <input type="email"
                    className={`form-control ${errors.email ? 'is-invalid' : ''}`}
                    id="email"
                    {...register('email', { required: 'Email is required', pattern: { value: /^\S+@\S+$/i, message: 'Invalid email address' } })} />
                  {errors.email && <div className="invalid-feedback">{errors.email.message}</div>}
                </div>
                <div className="mb-3">
                  <label htmlFor="password"
                    className="form-label">Password</label>
                  <input type="password"
                    className={`form-control ${errors.password ? 'is-invalid' : ''}`}
                    id="password"
                    {...register('password', { required: 'Password is required', minLength: { value: 6, message: 'Password must be at least 6 characters' } })} />
                  {errors.password && <div className="invalid-feedback">{errors.password.message}</div>}
                </div>
                {!isLoginMode && (
                  <div className="mb-3">
                    <label htmlFor="confirmPassword"
                      className="form-label">Confirm Password</label>
                    <input type="password"
                      className={`form-control ${errors.confirmPassword ? 'is-invalid' : ''}`}
                      id="confirmPassword"
                      {...register('confirmPassword', { required: 'Confirm Password is required', validate: value => value === password || 'Passwords do not match' })} />
                    {errors.confirmPassword && <div className="invalid-feedback">{errors.confirmPassword.message}</div>}
                  </div>
                )}
                <div className="d-grid">
                  <button type="submit"
                    className="btn btn-primary">{isLoginMode ? 'Login' : 'Sign Up'}</button>
                </div>
                <div className="text-center mt-3">
                  {isLoginMode ? (
                    <span>Don't have an account? <Link to="/signup">Sign up</Link></span>
                  ) : (
                    <span>Already have an account? <Link to="/login">Login</Link></span>
                  )}
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

// budget-app-angular/src/app/features/component/signup-login/signup-login.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { ReactiveFormsModule, FormGroup, FormBuilder, Validators, ValidationErrors } from '@angular/forms';
import { RouterModule, Router, ActivatedRoute } from '@angular/router';
import { User } from './models/User';
import { AuthService } from './services/auth.service';
import { HttpErrorResponse } from '@angular/common/http';

@Component({
  selector: 'app-signup-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule],
  templateUrl: './signup-login.component.html',
  styleUrls: ['./signup-login.component.css']
})
export class SignupLoginComponent implements OnInit {
  isLoginMode = true;
  loginForm: FormGroup;
  signupForm: FormGroup;
  errorMessage: string = '';

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
    });

    this.signupForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      confirmPassword: ['', [Validators.required]]
    }, {
      validators: [this.passwordMatchValidator]
    });
  }

  ngOnInit(): void {
    this.route.data.subscribe(data => {
      this.isLoginMode = data['isLoginMode'];
      this.errorMessage = '';
    });
  }

  get confirmPassword() {
    return this.signupForm.get('confirmPassword');
  }

  passwordMatchValidator(formGroup: FormGroup): ValidationErrors | null {
    const password = formGroup.get('password')?.value;
    const confirmPassword = formGroup.get('confirmPassword')?.value;
    return password === confirmPassword ? null : { mismatch: true };
  }

  hasError(form: FormGroup, controlName: string, errorName: string): boolean {
    const control = form.get(controlName);
    return !!((control?.touched || control?.dirty) && control?.hasError(errorName));
  }

  onLoginSubmit(): void {
    this.errorMessage = '';
    if (this.loginForm.invalid) {
      this.loginForm.markAllAsTouched();
      return;
    }

    const user: User = this.loginForm.value;

    this.authService.login(user).subscribe({
      error: (error: HttpErrorResponse) => {
        if (error.status === 0 || error.status === 401) {
          this.errorMessage = 'Invalid email or password.';
        } else {
          this.errorMessage = error.error?.message || 'An unknown error occurred.';
        }
      }
    });
  }

  onSignupSubmit(): void {
    this.errorMessage = '';
    if (this.signupForm.invalid) {
      this.signupForm.markAllAsTouched();
      return;
    }

    const user: User = {
      email: this.signupForm.value.email,
      password: this.signupForm.value.password
    };

    this.authService.register(user).subscribe({
      error: (error: HttpErrorResponse) => {
        if (error.status === 0) {
          this.errorMessage = 'Could not connect to the server.';
        } else if (error.error?.includes('already exists')) {
          this.errorMessage = 'This email address already exists.';
        } else {
          this.errorMessage = error.error?.message || 'An unknown error occurred.';
        }
      }
    });
  }
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-4">
            <div class="card mt-5">

                <!-- Login Form View -->
                <ng-container *ngIf="isLoginMode">
                    <div class="card-header bg-primary bg-opacity-75">
                        <h3 class="card-title mb-0 text-white">Login</h3>
                    </div>
                    <div class="card-body">
                        <div class="alert alert-danger" *ngIf="errorMessage">{{ errorMessage }}</div>
                        <form [formGroup]="loginForm" (ngSubmit)="onLoginSubmit()">
                            <div class="mb-3">
                                <label for="login-email" class="form-label">Email</label>
                                <input type="email" class="form-control" id="login-email" formControlName="email"
                                    [ngClass]="{'is-invalid': hasError(loginForm, 'email','required') || hasError(loginForm, 'email','email')}" />
                                <div class="invalid-feedback" *ngIf="hasError(loginForm, 'email', 'required')">
                                    Email is required
                                </div>
                                <div class="invalid-feedback" *ngIf="hasError(loginForm, 'email', 'email')">
                                    Please, enter a valid email address
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="login-password" class="form-label">Password</label>
                                <input type="password" class="form-control" id="login-password"
                                    formControlName="password"
                                    [ngClass]="{'is-invalid': hasError(loginForm, 'password','required') || hasError(loginForm, 'password','minlength')}" />
                                <div class="invalid-feedback" *ngIf="hasError(loginForm, 'password', 'required')">
                                    Password is required
                                </div>
                                <div class="invalid-feedback" *ngIf="hasError(loginForm, 'password', 'minlength')">
                                    Password must be at least 6 characters long
                                </div>
                            </div>
                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary" [disabled]="!loginForm.valid">
                                    Login
                                </button>
                            </div>
                            <div class="text-center mt-3">
                                You don't have an account? <a [routerLink]="'/signup'">Sign up</a>
                            </div>
                        </form>
                    </div>
                </ng-container>

                <!-- Signup Form View -->
                <ng-container *ngIf="!isLoginMode">
                    <div class="card-header bg-primary bg-opacity-75">
                        <h3 class="card-title mb-0 text-white">Sign Up</h3>
                    </div>
                    <div class="card-body">
                        <div class="alert alert-danger" *ngIf="errorMessage">{{ errorMessage }}</div>
                        <form [formGroup]="signupForm" (ngSubmit)="onSignupSubmit()">
                            <div class="mb-3">
                                <label for="signup-email" class="form-label">Email</label>
                                <input type="email" class="form-control" id="signup-email" formControlName="email"
                                    [ngClass]="{'is-invalid': hasError(signupForm, 'email','required') || hasError(signupForm, 'email','email')}" />
                                <div class="invalid-feedback" *ngIf="hasError(signupForm, 'email', 'required')">
                                    Email is required
                                </div>
                                <div class="invalid-feedback" *ngIf="hasError(signupForm, 'email', 'email')">
                                    Please, enter a valid email address
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="signup-password" class="form-label">Password</label>
                                <input type="password" class="form-control" id="signup-password"
                                    formControlName="password"
                                    [ngClass]="{'is-invalid': hasError(signupForm, 'password','required') || hasError(signupForm, 'password','minlength')}" />
                                <div class="invalid-feedback" *ngIf="hasError(signupForm, 'password', 'required')">
                                    Password is required
                                </div>
                                <div class="invalid-feedback" *ngIf="hasError(signupForm, 'password', 'minlength')">
                                    Password must be at least 6 characters long
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="confirmPassword" class="form-label">Confirm Password</label>
                                <input type="password" class="form-control" id="confirmPassword"
                                    formControlName="confirmPassword"
                                    [ngClass]="{'is-invalid': hasError(signupForm, 'confirmPassword','required') || (signupForm.hasError('mismatch') && confirmPassword?.touched)}" />
                                <div class="invalid-feedback"
                                    *ngIf="hasError(signupForm, 'confirmPassword','required')">
                                    Confirm Password is required
                                </div>
                                <div class="invalid-feedback"
                                    *ngIf="!hasError(signupForm, 'confirmPassword','required') && signupForm.hasError('mismatch') && confirmPassword?.touched">
                                    Passwords do not match.
                                </div>
                            </div>
                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary" [disabled]="!signupForm.valid">
                                    Sign up
                                </button>
                            </div>
                            <div class="text-center mt-3">
                                Already have an account? <a [routerLink]="'/login'">Login</a>
                            </div>
                        </form>
                    </div>
                </ng-container>

            </div>
        </div>
    </div>
</div>
